package by.tc.online_pharmacy.controller.command;


public enum CommandName {
    CHANGE_LOCALE,
    SIGN_IN,
    SIGN_UP,
    LOG_OUT,
    SHOW_DRUGS,
    SEARCH,
    SHOW_DRUGS_TO_ORDER,
    SHOW_DRUGS_TO_UPDATE,
    ADD_NEW_DRUG,
    ADD_DRUG_QUANTITY,
    REMOVE_DRUG,
    CHECKOUT,
    ORDER_WITHOUT_RECIPE,
    ORDER_WITH_RECIPE,
    PHARMACIST_SHOW_ORDER_LIST,
    CLIENT_SHOW_ORDER_LIST,
    SEND,
    CLIENT_CANCEL_ORDER,
    PHARMACIST_CANCEL_ORDER,
    SEND_RECIPE_EXTENSION_REQUEST,
    APPROVE,
    DENY,

    SEND_FEEDBACK
}
