package by.tc.online_pharmacy.resource;


public enum CommandName {

    //pages
    START_PAGE, SIGN_IN_PAGE, SIGN_UP_PAGE, GROUPS_TO_ORDER_PAGE, ORDER_BY_ERECIPE_PAGE,
    EXTEND_RECIPE_PAGE, GROUPS_TO_UPDATE_PAGE, ADD_DRUG_PAGE, WRONG_REQUEST_PAGE,

    //common
    CHANGE_LOCALE, SIGN_IN, LOG_OUT, SEARCH, SHOW_DRUGS,

    //pharmacist
    SHOW_DRUGS_TO_UPDATE, ADD_NEW_DRUG, ADD_DRUG_QUANTITY, REMOVE_DRUG,
    PHARMACIST_SHOW_ORDER_LIST, SEND, PHARMACIST_CANCEL_ORDER, SHOW_SALES_REPORT,

    //client
    SIGN_UP, ORDER_WITHOUT_RECIPE, ORDER_WITH_RECIPE, SHOW_DRUGS_TO_ORDER, SHOW_ERECIPE,
    CLIENT_SHOW_ORDER_LIST, CLIENT_CANCEL_ORDER, SEND_RECIPE_EXTENSION_REQUEST,
    REPORT_ABOUT_DELIVERY, SHOW_MESSAGES, DELETE_MESSAGE, SHOW_BALANCE, SHOW_SHOPPING_LIST,

    //doctor
    APPROVE, DENY, SHOW_RECIPE_EXTENSION_REQUESTS
}