-- MySQL Script generated by MySQL Workbench
-- 05/28/17 15:10:41
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pharmacy
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pharmacy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pharmacy` DEFAULT CHARACTER SET utf8 ;
USE `pharmacy` ;

-- -----------------------------------------------------
-- Table `pharmacy`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmacy`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `position` ENUM('doctor', 'pharmacist', 'client', 'admin') NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `patronymic` VARCHAR(45) NOT NULL,
  `mobile_phone` VARCHAR(20) NOT NULL,
  `password` CHAR(32) NOT NULL,
  `is_active` ENUM('yes', 'no') NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `mobile_phone_UNIQUE` (`mobile_phone` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pharmacy`.`pharm_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmacy`.`pharm_group` (
  `group` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`group`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pharmacy`.`drug`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmacy`.`drug` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `pharm_group` VARCHAR(45) NOT NULL,
  `form` ENUM('pills', 'capsules', 'powder', 'solution', 'mixture', 'suspension', 'aerosol', 'drops', 'spray', 'syrup', 'pastilles') NOT NULL,
  `drug_amount` VARCHAR(45) NOT NULL,
  `active_substances` TINYTEXT NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `dispensing` ENUM('on prescription', 'without prescription') NOT NULL,
  `price` DECIMAL(7,2) UNSIGNED NOT NULL,
  `quantity` INT UNSIGNED NOT NULL,
  `is_active` ENUM('yes', 'no') NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `drug_name_idx` (`name` ASC),
  INDEX `pharm_group_fk_idx` (`pharm_group` ASC),
  CONSTRAINT `pharm_group_fk`
    FOREIGN KEY (`pharm_group`)
    REFERENCES `pharmacy`.`pharm_group` (`group`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pharmacy`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmacy`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `client_id` INT NOT NULL,
  `pharmacist_id` INT NULL,
  `drug_id` INT NOT NULL,
  `quantity` INT UNSIGNED NOT NULL,
  `cost` DECIMAL(7,2) UNSIGNED NOT NULL,
  `request_date` TIMESTAMP NOT NULL,
  `response_date` TIMESTAMP NULL,
  `status` ENUM('new', 'sent', 'received', 'canceled') NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `client_id_fk_idx` (`client_id` ASC),
  INDEX `pharmacist_id_fk_idx` (`pharmacist_id` ASC),
  INDEX `drug_id_fk_idx` (`drug_id` ASC),
  INDEX `status_idx` (`status` ASC),
  CONSTRAINT `order_client_id_fk`
    FOREIGN KEY (`client_id`)
    REFERENCES `pharmacy`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `pharmacist_id_fk`
    FOREIGN KEY (`pharmacist_id`)
    REFERENCES `pharmacy`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `order_drug_id_fk`
    FOREIGN KEY (`drug_id`)
    REFERENCES `pharmacy`.`drug` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pharmacy`.`recipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmacy`.`recipe` (
  `code` VARCHAR(45) NOT NULL,
  `patient_id` INT NOT NULL,
  `doctor_id` INT NOT NULL,
  `drug_id` INT NOT NULL,
  `quantity` INT UNSIGNED NOT NULL,
  `start_date` TIMESTAMP NULL,
  `end_date` TIMESTAMP NULL,
  `status` ENUM('open', 'closed') NOT NULL,
  PRIMARY KEY (`code`),
  INDEX `end_date_idx` (`end_date` ASC),
  INDEX `drug_id_fk_idx` (`drug_id` ASC),
  CONSTRAINT `drug_id_fk`
    FOREIGN KEY (`drug_id`)
    REFERENCES `pharmacy`.`drug` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pharmacy`.`recipe_extension_request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmacy`.`recipe_extension_request` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `recipe_code` VARCHAR(45) NOT NULL,
  `client_id` INT NOT NULL,
  `doctor_id` INT NULL,
  `request_date` TIMESTAMP NOT NULL,
  `response_date` TIMESTAMP NULL,
  `status` ENUM('new', 'approved', 'denied') NOT NULL,
  `is_read` ENUM('yes', 'no') NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `recipe_code_fk_idx` (`recipe_code` ASC),
  CONSTRAINT `rer_recipe_code_fk`
    FOREIGN KEY (`recipe_code`)
    REFERENCES `pharmacy`.`recipe` (`code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pharmacy`.`order_recipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmacy`.`order_recipe` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `recipe_code` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `order_id_fk_idx` (`order_id` ASC),
  INDEX `recipe_code_fk_idx` (`recipe_code` ASC),
  CONSTRAINT `order_id_fk`
    FOREIGN KEY (`order_id`)
    REFERENCES `pharmacy`.`orders` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `o_r_recipe_code_fk`
    FOREIGN KEY (`recipe_code`)
    REFERENCES `pharmacy`.`recipe` (`code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pharmacy`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pharmacy`.`account` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `client_id` INT NOT NULL,
  `balance` DECIMAL(7,2) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `account_client_id_fk_idx` (`client_id` ASC),
  CONSTRAINT `account_client_id_fk`
    FOREIGN KEY (`client_id`)
    REFERENCES `pharmacy`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;