package by.tc.online_pharmacy.security;


public enum PharmacistCommand {
    SHOW_DRUGS_TO_UPDATE, ADD_NEW_DRUG, ADD_DRUG_QUANTITY, REMOVE_DRUG,
    PHARMACIST_SHOW_ORDER_LIST, SEND, PHARMACIST_CANCEL_ORDER, SHOW_SALES_REPORT,
    GROUPS_TO_UPDATE_PAGE, ADD_DRUG_PAGE
}
